# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Residence.create(name: 'Cinnamon College', latitude: 1.3067690480000000, longitude: 103.7735685000000000)
Residence.create(name: 'College of Alice and Peter Tan', latitude: 1.3076300000000000, longitude: 103.7731500000000000)
Residence.create(name: 'Eusoff Hall', latitude: 1.2932827670000000, longitude: 103.7702482000000000)
Residence.create(name: 'Kent Ridge Hall', latitude: 1.2919261110000000, longitude: 103.7745420000000000)
Residence.create(name: 'King Edward VII Hall', latitude: 1.2925201140000000, longitude: 103.7808893000000000)
Residence.create(name: 'Kuok Foundation House', latitude: 1.3003111180000000, longitude: 103.7736778000000000)
Residence.create(name: 'Prince George\'s Park Residences', latitude: 1.2909929190000000, longitude: 103.7812283000000000)
Residence.create(name: 'Raffles Hall', latitude: 1.2998727830000000, longitude: 103.7738292000000000)
Residence.create(name: 'Residence College 4', latitude: 1.3082100000000000, longitude: 103.7734100000000000)
Residence.create(name: 'Ridge View Residences', latitude: 1.2982096290000000, longitude: 103.7760838000000000)
Residence.create(name: 'Ridge View Tower Block', latitude: 1.2980293140000000, longitude: 103.7767474000000000)
Residence.create(name: 'Sheares Hall', latitude: 1.2910741950000000, longitude: 103.7756714000000000)
Residence.create(name: 'Tembusu College', latitude: 1.3062500000000000, longitude: 103.7736800000000000)
Residence.create(name: 'Temasek Hall', latitude: 1.2929035960000000, longitude: 103.7713867000000000)
Residence.create(name: 'UTown Residence', latitude: 1.3055020400000000, longitude: 103.7737984000000000)

faculty = Faculty.create(name: "Arts & Social Sciences")
Major.create(faculty: faculty, name: "Centre For Language Studies")
Major.create(faculty: faculty, name: "Chinese Studies")
Major.create(faculty: faculty, name: "Communications And New Media")
Major.create(faculty: faculty, name: "Dean's Office (Arts & Social Sc.)")
Major.create(faculty: faculty, name: "Economics")
Major.create(faculty: faculty, name: "English Language & Literature")
Major.create(faculty: faculty, name: "Geography")
Major.create(faculty: faculty, name: "History")
Major.create(faculty: faculty, name: "Japanese Studies")
Major.create(faculty: faculty, name: "Malay Studies")
Major.create(faculty: faculty, name: "Philosophy")
Major.create(faculty: faculty, name: "Political Science")
Major.create(faculty: faculty, name: "Psychology")
Major.create(faculty: faculty, name: "Social Work")
Major.create(faculty: faculty, name: "Sociology")
Major.create(faculty: faculty, name: "South Asian Studies Programme")
Major.create(faculty: faculty, name: "Southeast Asian Studies")
faculty = Faculty.create(name: "Dentistry")
Major.create(faculty: faculty, name: "Dentistry")
Major.create(faculty: faculty, name: "Division Of Graduate Dental Studies")
faculty = Faculty.create(name: "Duke-NUS Graduate Medical School S'pore")
Major.create(faculty: faculty, name: "Duke-NUS Graduate Medical School S'pore")
faculty = Faculty.create(name: "Engineering")
Major.create(faculty: faculty, name: "Bachelor Of Technology Programme")
Major.create(faculty: faculty, name: "Biomedical Engineering")
Major.create(faculty: faculty, name: "Chemical & Biomolecular Engineering")
Major.create(faculty: faculty, name: "Civil & Environmental Engineering")
Major.create(faculty: faculty, name: "Dean's Office (Engineering)")
Major.create(faculty: faculty, name: "Division Of Engineering And Tech Mgt")
Major.create(faculty: faculty, name: "Electrical & Computer Engineering")
Major.create(faculty: faculty, name: "Engineering Science Programme")
Major.create(faculty: faculty, name: "Industrial & Systems Engineering")
Major.create(faculty: faculty, name: "Materials Science And Engineering")
Major.create(faculty: faculty, name: "Mechanical Engineering")
faculty = Faculty.create(name: "Joint Multi-Disciplinary Programmes")
Major.create(faculty: faculty, name: "Computing & Engineering")
faculty = Faculty.create(name: "Law")
Major.create(faculty: faculty, name: "Law")
faculty = Faculty.create(name: "Lee Kuan Yew School Of Public Policy")
Major.create(faculty: faculty, name: "Lee Kuan Yew School Of Public Policy")
faculty = Faculty.create(name: "NUS Grad Sch For Integrative Sci & Engg")
Major.create(faculty: faculty, name: "NUS Grad Sch For Integrative Sci & Engg")
faculty = Faculty.create(name: "Non-Faculty-Based Departments")
Major.create(faculty: faculty, name: "College Of Alice & Peter Tan")
Major.create(faculty: faculty, name: "Ctr For English Language Communication")
Major.create(faculty: faculty, name: "Institute Of Systems Science")
Major.create(faculty: faculty, name: "Residential College 4")
Major.create(faculty: faculty, name: "Ridge View Residential College")
Major.create(faculty: faculty, name: "Temasek Defence Systems Institute")
Major.create(faculty: faculty, name: "Tembusu College")
faculty = Faculty.create(name: "Saw Swee Hock School Of Public Health")
Major.create(faculty: faculty, name: "Saw Swee Hock School Of Public Health")
faculty = Faculty.create(name: "School Of Business")
Major.create(faculty: faculty, name: "Accounting")
Major.create(faculty: faculty, name: "Dean's Office (Biz)")
Major.create(faculty: faculty, name: "Decision Sciences")
Major.create(faculty: faculty, name: "Finance")
Major.create(faculty: faculty, name: "Human Resource Management Unit")
Major.create(faculty: faculty, name: "Management And Organisation")
Major.create(faculty: faculty, name: "Marketing")
Major.create(faculty: faculty, name: "Strategy And Policy")
faculty = Faculty.create(name: "School Of Computing")
Major.create(faculty: faculty, name: "Computer Science")
Major.create(faculty: faculty, name: "Dean's Office (School Of Computing)")
Major.create(faculty: faculty, name: "Information Systems")
faculty = Faculty.create(name: "School Of Design And Environment")
Major.create(faculty: faculty, name: "Architecture")
Major.create(faculty: faculty, name: "Building")
Major.create(faculty: faculty, name: "Dean's Office (School Of Design & Env)")
Major.create(faculty: faculty, name: "Division Of Industrial Design")
Major.create(faculty: faculty, name: "Real Estate")
faculty = Faculty.create(name: "Science")
Major.create(faculty: faculty, name: "Biological Sciences")
Major.create(faculty: faculty, name: "Chemistry")
Major.create(faculty: faculty, name: "Dean's Office (Science)")
Major.create(faculty: faculty, name: "Mathematics")
Major.create(faculty: faculty, name: "Pharmacy")
Major.create(faculty: faculty, name: "Physics")
Major.create(faculty: faculty, name: "Statistics & Applied Probability")
faculty = Faculty.create(name: "Speciality Research Institutes/Centres")
Major.create(faculty: faculty, name: "Centre For Quantum Technologies")
Major.create(faculty: faculty, name: "Mechanobiology Institute")
Major.create(faculty: faculty, name: "Risk Management Institute")
Major.create(faculty: faculty, name: "The Logistics Institute - Asia Pacific")
faculty = Faculty.create(name: "University Administration")
Major.create(faculty: faculty, name: "Centre For Future-Ready Graduates")
faculty = Faculty.create(name: "University Scholars Programme")
Major.create(faculty: faculty, name: "University Scholars Programme")
faculty = Faculty.create(name: "Yale-NUS College")
Major.create(faculty: faculty, name: "Yale-NUS College")
faculty = Faculty.create(name: "Yong Loo Lin School Of Medicine")
Major.create(faculty: faculty, name: "Anatomy")
Major.create(faculty: faculty, name: "Biochemistry")
Major.create(faculty: faculty, name: "Dean's Office (Medicine)")
Major.create(faculty: faculty, name: "Division Of Graduate Medical Studies")
Major.create(faculty: faculty, name: "Microbiology")
Major.create(faculty: faculty, name: "Nursing/Alice Lee Ctr For Nursing Stud")
Major.create(faculty: faculty, name: "Pathology")
Major.create(faculty: faculty, name: "Pharmacology")
Major.create(faculty: faculty, name: "Physiology")
faculty = Faculty.create(name: "Yong Siew Toh Conservatory Of Music")
Major.create(faculty: faculty, name: "Yong Siew Toh Conservatory Of Music")

